---
name: JupyterLabPyscript
version: "0.0.2"
slug: jupyterlabpyscript
description: JupyterLab with Pyscript Kernel
url: https://github.com/iot49/addon-jupyter-pyscript
ingress: true
panel_icon: mdi:flask-outline
init: false
arch:
  - aarch64
  - amd64
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
